# Quelles sources d'information ?

Diverses sources d’information sont mobilisables pour répondre à votre question. En tant qu’étudiants, des informations que vous pourriez mobiliser assez vite et spontanément sont celles consignées dans vos notes et polycopiés de cours. Vos enseignants font déjà sur certains sujets le travail que vous essayez de faire, et les informations dont vous disposez sont peut-être déjà à jour. Il est également possible que les informations qui vous sont fournies par vos enseignants soient différentes de ce que vous voyez appliqué sur le terrain, ou que différents maîtres de stages appliquent des pratiques complètement différentes pour le même trouble de santé. Et parfois vos notes de cours sont trop imprécises pour répondre à votre questions (exemple : d’une note «antibiotiques» pour une maladie donnée sans indication de la molécule ou de la posologie).

D’autres sources d’informations à votre disposition sont la presse professionnelle, les congrès professionnels, les formations, les fiches techniques et communications produites par des groupes de travail, des commissions techniques d’organisations professionnelles ou par les entreprises qui commercialisent des produits. Enfin, une dernière source d’information à votre disposition est ce que l’on appelle la littérature scientifique.

Selon la provenance de l’information, sa nature et son contenu, vous établissez probablement déjà une hiérarchie et accordez plus ou moins de crédit à certaines sources et documents. La littérature scientifique internationale, notamment issue de journaux à comité de lecture, lorsqu’elle existe, est une source d’information qui devrait être privilégiée car son objectif est de produire des connaissances objectives à partir de données et de méthodes adaptées à la question de recherche.