# Trouver les informations

Un enjeu majeur pour l'obtention d'une réponse la plus juste possible est l'identification de toutes les études conduites sur la question d'intérêt. Or, les études ayant identifié un effet positif ou surprenant d'une pratique ou d'un traitement ont plus de chances d'être publiées. C'est ce que l'on appelle le biais de publication [@Easterbrook1991], pour lequel une multitude de facteurs explicatifs ont été identifiés. Premièrement, les auteurs d'une étude dans laquelle aucun effet significatif n'a été identifié ont une motivation moindre à rédiger et faire évaluer leurs résultats. On parle d'*effet tiroir*[^recherche_info-1]. Ensuite, les relecteurs des articles et les éditeurs des journaux peuvent se montrer moins intéressés par des études ne mettant en évidence aucun effet statistiquement significatif. En médecine humaine, il est parfois demandé aux scientifiques de pré-enregistrer les études, principalement les essais cliniques, avant qu'elles soient conduites pour limiter les impacts de ce biais[^recherche_info-2]. En toute rigueur, on devrait donc faire en sorte que toutes les études conduites sur la question d'intérêt, qu'elles aient été publiées dans des journaux scientifiques ou non, soient identifiées. Pour les documents non publiés dans les journaux scientifiques, on parle de littérature grise. Le pré-enregistrement des études simplifie l'identification de toutes les études conduites.

[^recherche_info-1]: Effet tiroir est traduit par *file drawer problem* en anglais.

[^recherche_info-2]: En anglais, on parle de preregistration. [Page Wikipedia correspondante](https://en.wikipedia.org/wiki/Preregistration_(science))

La façon la plus rigoureuse de conduire la recherche d'informations est de suivre la méthodologie des revues systématiques décrite dans le [chapitre -@sec-etude]. Ceci n'est bien souvent pas possible en pratique vétérinaire, faute de temps et parfois fautes d'articles sur des maladies rares ou peu étudiées. Des procédures allégées ont été proposées, notamment les *critically appraised topics* [@Brennan2020], où la recherche d'informations est moins exhaustive et l'évaluation des sources identifiées est moins poussées.

Dans l'esprit des *critically appraised topics*, dans le reste de cette partie, nous nous focalisons sur l'identification d'articles scientifiques dans une seule base de données.
